### ISSUE TITLE
code documentation vs. MMTF spec

### ISSUE THREAD

**Issue by speleo3** [rcsb/mmtf-c#24]
I like to raise a point for discussion.

Most of the (doxygen) code documentation describes the MMTF data model. In my opinion this is redundant with the MMTF spec and not necessary. I would expect that the C implementation is as close to the spec as possible, and I would read the spec rather than the doxygen documentation when working with the library. That basically means that e.g. the struct members in `mmtf_parser.h` don't need any documentation.

On the other hand, anything that is implementation specific needs clean doxygen documentation, of course. E.g. all public functions in `mmtf_parser.h`.

**Comment by josemduarte** [comment]
Agree, let's not repeat the spec but rather link to it from doxygen docs.

**Comment by speleo3** [comment]
@josemduarte I can take care of this (and #23) and will send a pull request soon

**Comment by josemduarte** [comment]
That'd be fantastic, thanks a lot!
