### ISSUE TITLE
Error in parsing float values with msgpack-c 2.1.1

### ISSUE THREAD

**Issue by gtauriello** [rcsb/mmtf-c#26]
When loading most of the test data (e.g. "./compile_and_run.sh data/173D.mmtf"), I get errors "Error in MMTF_parser_fetch_float: the entry encoded in the MMTF is not a float."

This happens when parsing the "resolution" and "rWork" fields of the mmtf.
It turns out that the "FLOAT" type is a 64-bit float and the C version of msgpack determines that the variable is a 32-bit float. Interestingly enough, the C++ version of msgpack (enabled here by defining "MMTF_MSGPACK_USE_CPP11") determined that the variables are 64-bit floats (hence no error there).

Given that I am not sure that we have full control over whether msgpack will use 32 or 64 bits for Float type variables (and they are stored in the "via" variable as double anyways), we should probably accept both. Hence, my proposed change is as follows:
```
float MMTF_parser_fetch_float(const msgpack_object* object) {
-    if (object->type != MMTF_MSGPACK_TYPE(FLOAT)) {
+    if (   object->type != MMTF_MSGPACK_TYPE(FLOAT32)
+        && object->type != MMTF_MSGPACK_TYPE(FLOAT64)) {
         fprintf(stderr, "Error in %s: the entry encoded in the MMTF is not a float.\n", __FUNCTION__);
         return NAN;
     }
```
Given the changelogs from msgpack-c, this might only work for versions 2.1.0 or newer, but they are deprecating the use of the "FLOAT" and "DOUBLE" types, so we should probably update too.
Alternatively, one may drop the check altogether and just blindly interpret the input as a floating point number...

**Comment by speleo3** [comment]
Good catch. Thoughts:

According to [MMTF spec](https://github.com/rcsb/mmtf/blob/master/spec.md#types), all floats are supposed to be 32bit. Of course this doesn't help if  **msgpack-c** before 2.1 only implements a 64bit type. The current implementation works for me with **msgpack-c** version 1.0 and later.

I wouldn't drop the check. A robust way to support different **msgpack-c** versions would be to hard code the enum value, instead of using the (new) `MSGPACK_OBJECT_FLOAT32` symbol.

```
 float MMTF_parser_fetch_float(const msgpack_object* object) {
-    if (object->type != MMTF_MSGPACK_TYPE(FLOAT)) {
+    switch (object->type) {
+    case /* FLOAT64 */ MMTF_MSGPACK_TYPE(FLOAT):
+    case /* FLOAT32 */ 0x0a: // msgpack-c >= 2.1
+        return (float)object->via.f64;
+    default:
         fprintf(stderr, "Error in %s: the entry encoded in the MMTF is not a float.\n", __FUNCTION__);
         return NAN;
     }
-
-    return (float)object->via.f64;
 }

```

**Comment by gtauriello** [comment]
Regarding the specs, I guess the trouble is that the [msgpack specs](https://github.com/msgpack/msgpack/blob/master/spec.md) defines the "Float" type as a 64-bit type (with the possibility to internally use 32-bit). So we might run into the 32 vs 64 bit issue anyways...
I am not sure if a hard-coded enum-value is a good idea for future maintainability and msgpack-support. I will see if there is some way to get a preprocessor version check of the msgpack library.
