### ISSUE TITLE
Unable to decode any MMTF file

### ISSUE THREAD

**Issue by jcz14** [rcsb/mmtf-c#31]
`Error in MMTF_unpack_from_msgpack_object: the entry encoded in the MMTF is not a map` is output from all the demo executables when provided with a valid MMTF file. The build environment is Ubuntu 16.04 x86-64, using the latest versions of MessagePack and GCC toolkit. Attempts to use older versions of MessagePack as well as alternate C++ compilers made no difference.

**Comment by speleo3** [comment]
mmtf-c requires msgpack-c >= 1.0.

I assume that you:

- compile against recent version of msgpack-c headers (e.g. 2.x from git repository)
- run with version 0.5.7 (libmsgpackc2 or libmsgpack3) from Ubuntu repository

That's how I can reproduce your error. Such mix and match can't be supported. You should uninstall version 0.5.7 and compile msgpack-c from source.

**Comment by dkoes** [comment]
That's it
