### ISSUE TITLE
bondOrderList/bondAtomList not required

### ISSUE THREAD

**Issue by danpf** [rcsb/mmtf-c#34]
Ran into this with pymol, getting segfaults if a group has no bondAtomList or bondOrderList. (HOH, O only group)

according to the 'new' spec mmtf should be able to handle groups that don't have the keys 

bondAtomList or bondOrderList, or bondResonanceList

I'm not sure how much you want mmtf-c to support of the new spec... but it would be nice :)

**Comment by speleo3** [comment]
v1.0: https://github.com/rcsb/mmtf/blob/v1.0/spec.md#grouplist
latest: https://github.com/rcsb/mmtf/blob/master/spec.md#grouplist
